site_name: Die Your Way Documentation
nav:
  - Home: index.md
  - Types:
    - Argument Types: argument_types.md
    - Data Types: data_types.md
    - DieYourWay JSON: dieyourway_json.md
  - Conditions:
    - Biome Conditions: biome_conditions.md
    - Block Conditions: block_conditions.md
    - Damage Conditions: damage_conditions.md
    - Entity Conditions: entity_conditions.md
    - Fluid Conditions: fluid_conditions.md
    - Item Conditions: item_conditions.md
    - Meta Conditions: meta_conditions.md
  - Miscellanous:
    - Commands: misc/commands.md
    - Vanilla Damage Sources: misc/vanilla_damage_sources.md 
theme:
    name: null
    custom_dir: mkdocs_windmill_dark
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true