site_name: DieYourWay Documentation
site_url: https://dieyourway.readthedocs.io
nav:
  - Home: index.md
  - Guides:
    - Creating a Message File: guides/create_file.md
    - Adding Arguments: guides/arguments.md
  - Types:
    - Argument Types: argument_types.md
    - Data Types: https://origins.readthedocs.io/en/latest/types/data_types/
    - DieYourWay JSON: dieyourway_json.md
  - Conditions:
    - Bi-entity Conditions: https://origins.readthedocs.io/en/latest/types/bientity_condition_types/
    - Biome Conditions: https://origins.readthedocs.io/en/latest/types/biome_condition_types/
    - Block Conditions: https://origins.readthedocs.io/en/latest/types/block_condition_types/
    - Damage Conditions: https://origins.readthedocs.io/en/latest/types/damage_condition_types/
    - Entity Conditions: entity_conditions.md
    - Fluid Conditions: https://origins.readthedocs.io/en/latest/types/fluid_condition_types/
    - Item Conditions: item_conditions.md
    - Meta Conditions: https://origins.readthedocs.io/en/latest/types/meta_condition_types/
  - Miscellanous:
    - Commands: misc/commands.md
    - Vanilla Damage Sources: https://origins.readthedocs.io/en/latest/misc/extras/damage_source_names/
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode  
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  logo: images/logo.png
  favicon: images/logo.png
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/MerchantPug/die-your-way
        name: DieYourWay GitHub
      - icon: fontawesome/brands/discord
        link: https://discord.gg/UBfEjsANNz
        name: Pug's Modzone Discord
markdown_extensions:
    - toc:
        separator: "_"
    - pymdownx.highlight:
        anchor_linenums: true
    - admonition
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences