site_name: DieYourWay Documentation
nav:
  - Home: index.md
  - Guides:
    - Creating a Message File: guides/create_file.md
    - Adding Arguments: guides/arguments.md
  - Types:
    - Argument Types: argument_types.md
    - Data Types: https://origins.readthedocs.io/en/latest/data_types/
    - DieYourWay JSON: dieyourway_json.md
  - Conditions:
    - Bi-entity Conditions: https://origins.readthedocs.io/en/latest/bientity_conditions/
    - Biome Conditions: https://origins.readthedocs.io/en/latest/biome_conditions/
    - Block Conditions: https://origins.readthedocs.io/en/latest/block_conditions/
    - Damage Conditions: https://origins.readthedocs.io/en/latest/damage_conditions/
    - Entity Conditions: entity_conditions.md
    - Fluid Conditions: https://origins.readthedocs.io/en/latest/fluid_conditions/
    - Item Conditions: item_conditions.md
    - Meta Conditions: https://origins.readthedocs.io/en/latest/meta_conditions/
  - Miscellanous:
    - Commands: misc/commands.md
    - Vanilla Damage Sources: https://origins.readthedocs.io/en/latest/misc/vanilla_damage_sources/
theme: readthedocs
separator: '_'